version: '3.9'

services:
  base:
    build:
      context: ./
      dockerfile: docker/base/Dockerfile
    image: todo-base
  app:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    image: todo-dev
    volumes:
#      - ./docker/dev/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/home/todo
    ports:
      - "8000:80"
    networks:
      - default
  web:
    image: nginx:1.22.0
    volumes:
      - .:/home/todo
      - ./docker/dev/vhost.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - todo-volume:/var/lib/postgresql/data:rw
#    ports:
#      - "5432:5432"

volumes:
  todo-volume:
